pipeline:
  identifier: Build_new_gosample_1738204819629
  name: Build new-gosample
  orgIdentifier: default
  projectIdentifier: samplayground
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: Samgithub
        repoName: new-gosample
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    connectorRef: samdockerhub
                    image: golang:1.22.11-alpine3.21
                    shell: Sh
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestcoverage
                  name: go_test_coverage
                  spec:
                    connectorRef: samdockerhub
                    image: golang:1.22.11-alpine3.21
                    shell: Sh
                    command: go test -coverprofile=coverage.out ./...
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotestreport
                  name: go_test_report
                  spec:
                    connectorRef: samdockerhub
                    image: golang:1.22.11-alpine3.21
                    shell: Sh
                    command: "export GOBIN=/home/harness/go/bin\n\t\texport PATH=/home/harness/go/bin:$PATH\n\t\techo $PATH\n\t\tgo install github.com/jstemmer/go-junit-report/v2@latest\n\t\tgo test -v 2>&1 ./... | go-junit-report -set-exit-code > report.xml"
                    reports:
                      type: JUnit
                      spec:
                        paths:
                          - /harness/report.xml
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: samdockerhub
                    repo: samarthsud/newgosampl
                    tags:
                      - latest
                    caching: true
                  timeout: ""
                  type: BuildAndPushDockerRegistry
              - step:
                  type: SscaOrchestration
                  name: SBOM Orchestration_1
                  identifier: SBOMOrchestration_1
                  spec:
                    mode: generation
                    tool:
                      type: Syft
                      spec:
                        format: cyclonedx-json
                    source:
                      type: docker
                      spec:
                        connector: samdockerhub
                        image: samarthsud/newgosampl:latest
                    attestation:
                      type: cosign
                      spec:
                        privateKey: sam-private-key
                        password: sam-cosign-password
                    sbom_drift:
                      base: last_generated_sbom
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
              - step:
                  type: SscaArtifactSigning
                  name: Artifact Signing_1
                  identifier: ArtifactSigning_1
                  spec:
                    source:
                      type: docker
                      spec:
                        connector: samdockerhub
                        image: samarthsud/newgosampl:latest
                    signing:
                      type: cosign
                      spec:
                        private_key: sam-private-key
                        password: sam-cosign-password
                    uploadSignature:
                      upload: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kubernetes_connector_for_at
              namespace: ssca-at
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
        type: CI
